name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get install rpm
    wget https://github.com/aquasecurity/trivy/releases/download/latest/trivy_latest_Linux-64bit.deb
    sudo dpkg -i trivy_latest_Linux-64bit.deb
  displayName: 'Run a one-line script'

