name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  trivyVersion: 0.9.1

steps:
- script: |
    curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin
  displayName: 'Download and install Trivy'

- task: CmdLine@2
  displayName: "Run trivy scan"
  inputs:
    script: |
      trivy image --format template --template "@contrib/junit.tpl" -o junit-report-high.xml --exit-code 0 --severity MEDIUM,HIGH knqyf263/vuln-image:1.2.3
      trivy image --format template --template "@contrib/junit.tpl" -o junit-report-critical.xml --exit-code 1 --severity CRITICAL knqyf263/vuln-image:1.2.3

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junit-*.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true
    testRunTitle: 'Trivy'
  condition: 'always()'