name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  trivyVersion: 0.9.1

steps:
- script: |
    sudo apt-get install rpm
    wget https://github.com/aquasecurity/trivy/releases/download/v$(trivyVersion)/trivy_$(trivyVersion)_Linux-64bit.deb
    sudo dpkg -i trivy_$(trivyVersion)_Linux-64bit.deb
  displayName: 'Download and install Trivy'

- task: CmdLine@2
  displayName: "Run trivy scan"
  inputs:
    script: |
      trivy image --format template --template "@contrib/junit.tpl" -o junit-report-high.xml --exit-code 0 --severity MEDIUM,HIGH knqyf263/vuln-image:1.2.3
      trivy image --format template --template "@contrib/junit.tpl" -o junit-report-critical.xml --exit-code 1 --severity CRITICAL knqyf263/vuln-image:1.2.3

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true
    testRunTitle: 'Trivy'