# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git clone https://github.com/aquasecurity/trivy
    export GO111MODULE=on
  displayName: 'Clone Trivy'

- task: Go@0
  displayName: "Install Trivy"
  inputs:
    command: 'custom'
    customCommand: 'install'
    workingDirectory: '$(System.DefaultWorkingDirectory)/trivy/cmd/trivy'

- task: CmdLine@2
  inputs:
    script: 'trivy -v'
